name: firebridge
version: 6.8.0-dev.1
description: An experimental wrapper around Discord's API for user accounts.
homepage: https://github.com/openbonfire/firebridge
repository: https://github.com/openbonfire/firebridge
issue_tracker: https://github.com/openbonfire/firebridge/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.1.0"

dependencies:
  http: ^1.6.0
  logging: ^1.3.0
  path: ^1.9.1
  eterl: ^1.1.0
  runtime_type: ^1.1.0
  meta: ^1.16.0
  oauth2: ^2.0.5
  dart_mappable: ^4.6.1

dev_dependencies:
  test: ^1.25.14
  lints: ^2.1.1
  nock: ^1.2.3
  mocktail: ^1.0.4
  matcher: ^0.12.17
  string_similarity: ^2.1.1
  build_runner: ^2.10.4
  dart_mappable_builder: ^4.6.1
